### PR TITLE
add test for ocm_handle_root_policy_duration metric

### PR DESCRIPTION
**Pull request by willkutler**
ref:
- https://issues.redhat.com/browse/ACM-2513

Signed-off-by: Will Kutler <wkutler@redhat.com>

### CODE REVIEW

**Comment by dhaiducek** [comment]
@willkutler Would you please add the Jira issue URL to the commit message so that it can be tracked in `stolostron`?

**Comment by willkutler** [comment]
> @willkutler Would you please add the Jira issue URL to the commit message so that it can be tracked in `stolostron`?

Done!

**Review by dhaiducek — CHANGES_REQUESTED** [review]
I think this looks good, but since it's being combined with another test, would you consider:

- Renaming the file: `case14_templates_metrics_test.go` --> `case14_root_policy_metrics_test.go`
- Rewording the root `Describe`: `"Test policy template metrics"` --> `"Test root policy metrics"`

I think that'd be clearer now that there are two metrics types in the same test. What do you think?

**Comment by willkutler** [comment]
@dhaiducek looks good to me! I just made those rewording changes and squashed

**Review by dhaiducek — APPROVED** [review]
LGTM! Thanks, @willkutler!

**Pull request merged**
