### PR TITLE
Modify the incorrect URLlink in the README.md

### PR DESCRIPTION
**Pull request by levinwang88**
This url link [https://github.com/open-cluster-management-io/governance-policy-framework](url) cann't be access currently.
I have modified it to the correct URL link, Can anyone help me review this?

### CODE REVIEW

**Review by dhaiducek — APPROVED** [review]
Thanks for the update, @levinwang88!

**Comment by dhaiducek** [comment]
@levinwang88 Looks like the commits are missing the DCO signoff. To fix it, since there's only one commit, you should be able to run `git commit --amend --signoff` to add the signoff to the commit.

**Comment by wangglbj** [comment]
Hello dhaiducek, I have resubmitted a PR because the wrong account was used for this PR submission, can you cancel or delete it for me, thank you.

**Pull request closed without merging**
