### PR TITLE
Use testcase-scoped variables

### PR DESCRIPTION
**Pull request by dhaiducek**
...because unnecessary package-level variables are a no-no.

### CODE REVIEW

**Comment by gparvin** [comment]
/hold
in case the tests are flaky and you're still working on something, but this looks like nice cleanup work.  Thanks!
/lgtm

**Comment by dhaiducek** [comment]
> /hold in case the tests are flaky and you're still working on something, but this looks like nice cleanup work. Thanks! /lgtm

Thanks! It is a flake, but doesn't seem to be one I caused. Re-running...

**Comment by dhaiducek** [comment]
@gparvin The merge is waiting for a GitHub review also.

**Review by JustinKuli — APPROVED** [review]
Excellent!

**Pull request merged**
